### PR TITLE
Fix flake8 warnings

### PR DESCRIPTION
**Pull request by jbcrail**

### CODE REVIEW

**Comment by quasiben** [comment]
@jbcrail do you think travis should fail if flake8 fails ?

**Comment by quasiben** [comment]
Also, Thanks!

**Comment by mrocklin** [comment]
Yeah, nice.  A flake8 PR == <3 :)

**Comment by jbcrail** [comment]
@quasiben Yes, I'm partial to making Travis fail on any flake8 errors/warnings.

When resolving flake8 issues, I found an undefined method call (`copy_`) in commit b17ff99. The flake8 error uncovered an issue that would've arisen eventually (the method isn't invoked at this time).

**Comment by quasiben** [comment]
@jbcrail are there other files you want to fix ? should we agree on some linting styles (column limits)  and ignore versioneer.py ? I'm +1 on failing travis is linting fails, do you want to add that as well ?  Happy to do all these thing but thought I'd ask since you are well into fixing these errors :)

**Comment by jbcrail** [comment]
@quasiben I'm finished updating the files now that flake8 passes.

I just noticed that you're using YAPF and certainly want to stick with the project's agreed-upon styling. I had originally set flake8 to use 119 (Django default), but I can update flake8 to use YAPF's defined column width of 120. I've already updated Travis to fail on flake8 errors/warnings. I also can update Travis to run flake8 only on the `dask_ec2` directory.

After making these changes, should I run YAPF to format the code?

**Comment by quasiben** [comment]
@jbcrail, apologies for letting this drag on.  I think we should merge this and remove YAPF.  Thank you so much for this contribution!

**Comment by quasiben** [comment]
merging

**Pull request merged**
